# -*- coding: utf-8 -*-
"""DataImmersion-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_1IKTFi0doiRHFZmo9R1Yk9km9wOLIn
"""

import pandas as pd

data_url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"

data = pd.read_csv(data_url)

data.head()

data.sample(10) # Outputs a 'Data frame'

type(data)

data["Bairro"]

type(data["Bairro"])

data["Bairro"][1288]

data.info()

data.Metragem.mean()

data["Metragem"].mean()

sum(data["Bairro"] == "Vila Mariana") # Verifying if in the dataset exists a certain string

has_properties_in_vila_mariana = (data["Bairro"] == "Vila Mariana")
has_properties_in_vila_mariana

properties_in_vila_mariana = data[has_properties_in_vila_mariana]
properties_in_vila_mariana

properties_in_vila_mariana["Metragem"].mean()

data["Bairro"].value_counts()

number_of_district = data["Bairro"].value_counts()
 
number_of_district.head(10).plot.bar()
