# -*- coding: utf-8 -*-
"""DataImmersion-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11MBS2O0QOpPzeRIozgZgKCFXcrG2hV_G
"""

import pandas as pd

data_url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"

data = pd.read_csv(data_url)

data.head()

data.sample(10) # Outputs a 'Data frame'

type(data)

data["Bairro"]

data[["Bairro", "Valor"]]

type(data["Bairro"])

data["Bairro"][1288]

data.info()

data.Metragem.mean()

data["Metragem"].mean()

sum(data["Bairro"] == "Vila Mariana") # Verifying if in the dataset exists a certain string

has_properties_in_vila_mariana = (data["Bairro"] == "Vila Mariana")
has_properties_in_vila_mariana

properties_in_vila_mariana = data[has_properties_in_vila_mariana]
properties_in_vila_mariana

properties_in_vila_mariana["Metragem"].mean()

data["Bairro"].value_counts()

number_of_district = data["Bairro"].value_counts()
 
 number_of_district.head(10).plot.bar()

data["Valor"][0]

data["Valor"][0].split()

data["Valor"].str.split(expand = True)

data["Valor"].str.split(expand = True)[0].unique()

data["Valor"].str.split(expand = True)[1].unique()

data["Valor"].str.split(expand = True)[2].unique()

data[["Currency", "Announced_Value", "Type_Advertisement"]] = data["Valor"].str.split(expand = True)
data.head()

data[data["Type_Advertisement"].isnull()]["Type_Advertisement"].unique() # Verify if it has only 'None' values

properties_to_sale = data[data["Type_Advertisement"].isnull()]
properties_to_sale

properties_to_sale.info()

properties_to_sale["Announced_Value"].str.replace(".", "").astype(float)

properties_to_sale["Announced_Value_Converted"] = properties_to_sale["Announced_Value"].str.replace(".", "").astype(float)
properties_to_sale.info()

properties_to_sale["Announced_Value_Converted"].plot.hist(bins = 50)

properties_to_sale.describe()

pd.describe_option()

pd.set_option("display.precision", 2)
pd.set_option("display.float_format", lambda x: "%.2f" % x)
properties_to_sale.describe()

properties_to_sale[["Rua", "Bairro", "Cidade"]].describe(include = "all")

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))

sns.set()
ax = sns.histplot(data = properties_to_sale, x = "Announced_Value_Converted", kde = True)
ax.set_title("Histogram - Properties value")

plt.xlim((-50, 10000000))
plt.show()